### ISSUE TITLE
Files published unintentionally

### ISSUE THREAD

**Issue by ManuInNZ** [vfarcic/crossplane-tutorial#1]
Hi Master 

Maybe I should say 'Hi Main', bad joke sorry.

Even though they are listed in your gitignore, you have published the `kubeconfig.yaml` and `gke_gcloud_auth_plugin_cache`.

Is that on purpose ?

Looking forward for the matching video.

**Comment by vfarcic** [comment]
I forgot to add those to `.gitignore`. It's not a problem though since I always create a new project, do my thing, and remove it before I push changes to Git, so nothing was really exposed.

It'll take a while for the video since that's a very long training material and it'll take me quite a while to finish the material and then start recording.
